### ISSUE TITLE
Scheduled tasks displayed with Start icon

### ISSUE THREAD

**Issue by claremacrae** [702573N/Obsidian-Tasks-Calendar#10]
Hi, I have a fix for this ~~which is ready to submit as a PR. I just wanted to log the bug first, to explain the PR....~~

Repro:

1. Create a file with these tasks:

```text
- [ ] I have a 📅 Due Date 📅 2022-10-24
- [ ] I have a ⏳ Scheduled Date ⏳ 2022-10-24
- [ ] I have a 🛫  Start Date 🛫 2022-10-24
```

2. Create a calendar, such as:

````js
```dataviewjs
dv.view("_meta/_scripts/dvjs/tasks_calendar", {pages: "00 - Indexes/01-05 Calendars", view: "agenda", firstDayOfWeek: 1, options: "noDone"});
```
````

3. Switch to reading mode:

![image](https://user-images.githubusercontent.com/4840096/197624864-9e51ccd2-8e27-4686-bc7c-0bbd96b48fd3.png)

Note the Start icon at the start of the Scheduled Date line.

**Comment by claremacrae** [comment]
Apologies - I'm struggling to create the PR, as my editor is stripping off all the spaces at the end of a lot of lines - so the PR would have reformatting changes as well, which I really don't want.

If you could like to copy the change, it was to change this - so `start` changed to `scheduled` at the end of the line:

```js
	for (var t=0; t<scheduled.length; t++) {cellContent += setTask(scheduled[t], "start")};
```

to this:

```js
	for (var t=0; t<scheduled.length; t++) {cellContent += setTask(scheduled[t], "scheduled")};
```

**Comment by 702573N** [comment]
Thank you very much Clare. I fixed this issue in the view.js and will be rolled out with the next release.
