### ISSUE TITLE
Support navigating to corresponding line of task when clicking

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Calendar#11]
With version 1.1.4, one cannot navigate to the corresponding line of the original task by clicking the task text. One cannot do this when opening the task with the Hover Editor plugin, either. On the other hand, for the results given by DataviewJS, one can achieve the first point.

Therefore, it would be great if something like this can be supported for easier navigation to original task locations.

**Comment by 702573N** [comment]
Fixed in latest view.js:
[https://github.com/702573N/Obsidian-Tasks-Calendar/blob/main/tasksCalendar/view.js](url)

**Comment by wenlzhang** [comment]
It seems that one can navigate to the corresponding header but not the specific line of the original task?

**Comment by 702573N** [comment]
That functionality was never part of tasksCalendar but is on my personal wish list. Unfortunately this is a little complex and takes time.
