### ISSUE TITLE
icon to step through views

### ISSUE THREAD

**Issue by pcause** [702573N/Obsidian-Tasks-Calendar#12]
You nicely added the filer icon to switch on/off display of done items.  THANKS.  It gave me the idea of having perhaps a calendar icon and on each click it switches the calendar to a different view.  month/agenda/widget.

Sorry to keep asking for features but this code is *so* useful.

**Comment by 702573N** [comment]
I also had this idea and it should be realized in the upper left corner, where I first put the placeholder. A little patience and also this function will facilitate your everyday work.
