### ISSUE TITLE
Priority order in Tasks plugin

### ISSUE THREAD

**Issue by claremacrae** [702573N/Obsidian-Tasks-Calendar#13]
I really like the new sort order, where it sorts first by priority then by description - very nice.

## Tasks order of priorities

In case you haven't seen, the priority order in Tasks is [documented here](https://obsidian-tasks-group.github.io/obsidian-tasks/getting-started/priority/)

The non-obvious thing is that Low priority is lower than No priority:

> If a task has no priority at all, it is considered between low and medium priority. This means that the priority of 🔽 low tasks is considered lower than the priority of tasks without any specific priority. The idea is that you can easily filter out unimportant tasks without needing to assign a priority to all relevant tasks.

This picture shows the difference in sort order by priority, which will affect people who use Low priority in tasks. The differences are marked in red...

![image](https://user-images.githubusercontent.com/4840096/197861896-d7a650c9-b9b6-4f02-aef0-f906d7340d35.png)

## Possible fix

If you feel inclined to look at it, I think that with your code, the fix is easy... (I have tested it and it works)

```diff
--- a/Migration Test/_meta/_scripts/dvjs/tasks_calendar/view.js 
+++ b/Migration Test/_meta/_scripts/dvjs/tasks_calendar/view.js 
@@ -85,7 +85,7 @@ function getMeta(tasks) {
                };
                var lowMatch = taskText.indexOf("🔽");
                if (lowMatch>-1) {
-                       tasks[i].priority = "C";
+                       tasks[i].priority = "D";
                };
                var mediumMatch = taskText.indexOf("🔼");
                if (mediumMatch>-1) {
@@ -96,7 +96,9 @@ function getMeta(tasks) {
                        tasks[i].priority = "A";
                };
                if (lowMatch<0 && mediumMatch<0 && highMatch<0) {
-                       tasks[i].priority = "D"; // set prio D to all tasks don't have a prio
+                       // No priority is just above Low priority in Tasks:
+                       // https://obsidian-tasks-group.github.io/obsidian-tasks/getting-started/priority/
+                       tasks[i].priority = "C";
                }
                if (globalTaskFilter) { // remove global task filter
                        tasks[i].text = tasks[i].text.replaceAll(globalTaskFilter,"");
```

**Comment by claremacrae** [comment]
In case it helps with testing, here are the tasks I used:

```text
- [ ] High ⏫  📅 2022-10-24
- [ ] Medium 🔼  📅 2022-10-24
- [ ] None 📅 2022-10-24
- [ ] Low 🔽  📅 2022-10-24
```

**Comment by 702573N** [comment]
Oops. I don't use the priorities myself. For this reason, I mistakenly assigned the ranking of priorities. Sorry for that. Will be fixed of course.
