### ISSUE TITLE
Brat installation files missing

### ISSUE THREAD

**Issue by dxcore35** [702573N/Obsidian-Tasks-Calendar#18]
Please add the required files for installation via Brat 🙏🏻

# Error 1
BRAT
702573N/Obsidian-Tasks-Calendar
This does not seem to be an obsidian plugin, as there is no manifest.json file.

# Error 2

BRAT
702573N/Obsidian-Tasks-Calendar
A manifest.json or manifest-beta.json file does not exist in the root directory of the repository. This plugin cannot be installed.

**Comment by 702573N** [comment]
This is NOT a plugin, as explained in detail in the readme, but a code snippet for a view, implemented with the dataview-plugin. For installation instructions take a look at the readme.

**Comment by dxcore35** [comment]
Thank you!
