### ISSUE TITLE
Assign task date based on daily note (also undone tasks)

### ISSUE THREAD

**Issue by dxcore35** [702573N/Obsidian-Tasks-Calendar#19]
Please allow options
- to use the date from daily note filename for task (where there is no date)
- the ability to show task that are not done (the option: options: "noDone" - is not working for me)

# Example:

file name: 2022-10-21.md

Content:

- [ ] Task1
- [ ] Task2
- [ ] Task3

# Output

- Same like on the screenshot with exception that tasks are not checked
- Tasks are listed in order how they are listed in file

![Screenshot 2022-10-30 at 13 25 04](https://user-images.githubusercontent.com/7279156/198875987-89c51eb6-9152-44d0-ab17-6bdd04d37a68.jpg)

**Comment by dxcore35** [comment]
- I updated to version 1.2
- I defined daily notes folder: `dailyNoteFolder: "DIARY/DAYS"`
- There are no new daily notes (without date)

Is there some extra parameter to enable it?

**Comment by 702573N** [comment]
First of all the dailyNoteFolder paramter is only used to define the default folder for NEW daily notes created by clicking on cell name if no file exist.
Second, the option `noDailyNotes` hides all daily notes inside the calendar. Don't use this option if you would like to see your daily notes inside the calendar.
Third, tasks inside your daily notes must be set as tasks `- [ ] Test` and not as list `- Test`
Fourth, your daily notes must be named by the default syntax `YYYY-MM-DD`.

![diary days](https://user-images.githubusercontent.com/59178587/199003063-adaaff2b-c9e0-4525-846a-1a29faf08c9e.png)

**Comment by 702573N** [comment]
I have used your dataviewjs code line in my personal vault and get all my daily notes.
Have you completely closed and restarted obsidian once since installing the update?

**Comment by dxcore35** [comment]
Restarted obsidian fixed the problem! It works. Amazing work thank you very much!

**Comment by 702573N** [comment]
Oh my god, I was starting to panic. Nice that it works now.
