### ISSUE TITLE
Support showing task count for current calendar view

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Calendar#23]
It would be great if this can be supported.

**Comment by 702573N** [comment]
Do you have any suggestions on how and where this should be displayed in the monthly and/or weekly calendar?

**Comment by wenlzhang** [comment]
I would imagine three options for the count for now: incomplete tasks, completed tasks, both of them. One can select the option. In the future, there can be more options for other task statuses.

In the figure below, I drafted a possible location for the task count. Also, the icons for switching views are moved. One can select the desired count option from a dropdown menu, if possible. One can also set a default option in 'options'.

The method above should work for both week and month views.

<img width="1115" alt="Tasks Calendar" src="https://user-images.githubusercontent.com/44930227/200119990-5b64c459-ead9-4607-bd8e-77c3682aa6cb.png">
