### ISSUE TITLE
option to not show completed tasks

### ISSUE THREAD

**Issue by pcause** [702573N/Obsidian-Tasks-Calendar#3]
can you add an option to not display completed tasks.  best would be to add a toggle to the display that could toggle done on/off, but an option would be great.  seems just adding the option and then an if/else around the first 3 lines that either gets the done tasks or returns an empty done.

**Comment by 702573N** [comment]
The latest release 1.1.1 contains options to hide specific tasks: due, done, start, recurrence, scheduled. You have to use this as option with „no“ in front like noDone, noDue, noStart. Take a look at the readme.

The toggle is a nice idea and I would like to play with it.

**Comment by 702573N** [comment]
The latest release 1.1.2 contains a filter-icon on the upper-right corner to hide/show completed/done tasks. With ´options: "noDone"´ you can set hidding completed tasks as default filter.
