### ISSUE TITLE
Support hiding inline fields from task description

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Calendar#4]
Would it be possible to inline fields from task description? This would make it cleaner to see all tasks in calendar view. For example, `[created::2022-10-24]` can be hidden by using `hideCreated` in the `option`?

**Comment by 702573N** [comment]
I am not sure I understand the request correctly. Do you want to display meta information about the task, which is not represented in the task text, or do you want to display manually entered inline fields in the calendar-view? Manually inserted inline-fields in task-texts are already displayed and not hidden. On desktop devices, the mouse can be hovered over the task to display the complete task-text. Or do you want exactly that, that these inline-fields are NOT to be seen in the task-text and thus everything becomes clearer?

**Comment by 702573N** [comment]
Thanks for the feedback. I would implement a global option to hide all inline fields. Here it is not possible to distinguish between different fields. Is the display of the full text (including the inline fields) really necessary when hovering, if you have chosen not to display this information in the option?

**Comment by wenlzhang** [comment]
> Is the display of the full text (including the inline fields) really necessary when hovering, if you have chosen not to display this information in the option?

On a second thought, showing all inline fields when hovering seems not that necessary for my workflow, as I would usually use the Hover Editor plugin to navigate to the original location of the tasks.

**Comment by 702573N** [comment]
Released with 1.1.3
