### ISSUE TITLE
1.4.2 display is broken

### ISSUE THREAD

**Issue by pcause** [702573N/Obsidian-Tasks-Calendar#40]
Loaded 1.4.2, restarted obsidian

![image](https://user-images.githubusercontent.com/1071479/209135257-cc3aac5d-de1a-4e61-8968-6f0879afa79e.png)

settings:  {pages: "", view: "week", firstDayOfWeek: 7, options: "style3 nolineClamp noFilename noCounter noDone"}

**Comment by 702573N** [comment]
Options are case sensitive. Please write `noLineClamp` instead of `nolineClamp`.
