### ISSUE TITLE
Display is broken

### ISSUE THREAD

**Issue by Sriramgireesh** [702573N/Obsidian-Tasks-Calendar#42]
I copied and pasted 
```dataviewjs
await dv.view("tasksCalendar", {pages: "", view: "month", firstDayOfWeek: "1", options: "style1"})
```
This is the output. I am not sure what I am doing wrong
![image](https://user-images.githubusercontent.com/66196487/209161183-8e5947fd-c306-4dda-bf0e-c01ab8a1043d.png)

![image](https://user-images.githubusercontent.com/66196487/209161290-ef070bb4-31d0-4d48-8d04-0fc56a9de827.png)

**Comment by 702573N** [comment]
Your posted code works pretty well on my devices. Please completely close und restart Obsidian!

**Comment by Sriramgireesh** [comment]
> Your posted code works pretty well on my devices. Please completely close und restart Obsidian!

Hi, I downloaded the files js and css files again and it is working fine now. Thankyou
