### ISSUE TITLE
Mistake from my side?

### ISSUE THREAD

**Issue by radiba** [702573N/Obsidian-Tasks-Calendar#45]
Hi,
Thank you for your work, I use following code:

> ```dataviewjs
> dv.view("tasksCalendar", {pages: "", view: "month", firstDayOfWeek: 1, options: "style1"})
> ```

and I receive following output:

> _Dataview: Error while executing view 'tasksCalendar/view.js'.
> 
> TypeError: rootNode.querySelector is not a function_

Where is mistaken?

**Comment by 702573N** [comment]
With the latest version the parameter firstDayOfWeek has to be inside quotes:

firstDayOfWeek: "1"

Best regards

**Comment by radiba** [comment]
Thank you for answering so quickly. I take note and I change parameter in source as follows:
```dataviewjs
dv.view("tasksCalendar", {pages: "", view: "month", firstDayOfWeek: "1", options: ""})
```
And I receive following:

```
Dataview: Error while executing view 'tasksCalendar/view.js'.

TypeError: rootNode.querySelector is not a function
```

**Comment by 702573N** [comment]
You forgot to enter "style1" (or another style) inside options parameter. But by entering this you have to see a detailed error message. Because you don't see that, it seems there is something other wrong in your vault. Can you enter the missing style and completely close and restart Obsidian!

**Comment by radiba** [comment]
sorry It was a error on copy-paste, My pice of code had style definition:
```dataviewjs
dv.view("tasksCalendar", {pages: "", view: "month", firstDayOfWeek: "1", options: "style1"})
```
I've restarted obsidian and I get the same message:
```
Dataview: Error while executing view 'tasksCalendar/view.js'.

TypeError: rootNode.querySelector is not a function
```

**Comment by radiba** [comment]
How can I provide you more information regarding my vault?

**Comment by 702573N** [comment]
Can you download to complete ZIP from GitHub and paste the unpacked folder (including view.css, view.js and demo_file.md) to your vault. Then (without moving or renaming any files) open the demo_file.md. What happens after that?

**Comment by radiba** [comment]
Thank you so much, It's solved, I've some plugins out of date. It works now!!
It's a great solution!!!

**Comment by radiba** [comment]
It's solved it was an out of date regarding plugins

**Comment by itshappeningbaby** [comment]
Yihaa ! thanks @702573N . Worked for me too!
