### ISSUE TITLE
Cannot show as List if showing dataviewjs with view "list"

### ISSUE THREAD

**Issue by profucius** [702573N/Obsidian-Tasks-Calendar#47]
The dataview js I am using is below. All I did was change the word "month" to "list" according to your working example.
`````
```dataviewjs
await dv.view("Tasks Calendar", {pages: "", view: "list", firstDayOfWeek: "1", options: "style1"})
```
`````

The error response is below:

`Dataview: Error while executing view 'Tasks Calendar/view.js'.`
`ReferenceError: selectedList is not defined`

**Comment by 702573N** [comment]
Sorry, I fixed this bug:
[view.js](https://github.com/702573N/Obsidian-Tasks-Calendar/blob/main/tasksCalendar/view.js)
