### ISSUE TITLE
Display week/month calendar based on specific file name or time frame

### ISSUE THREAD

**Issue by foenixp** [702573N/Obsidian-Tasks-Calendar#49]
Hi,
I posted this question on the wrong place, so I re-posted it here.
This is a great snippet I have been dreaming of. Thank you so much for creating it!
I wonder if this feature could be done: I want to add the weekly calendar view to my weekly note (my weekly note named 2023-W03), and the calendar would display the week of that note, instead of the current week. For example, right now is Week 3, so when I open Week 1 weekly note, the calendar should show Week 1 tasks calendar. But right now it always shows the current Week 3 no matter where I put the dataviewjs code.

**Comment by 702573N** [comment]
Hi,
you can use the 'startPosition: ""' parameter to do that.

For example:
```dataviewjs
await dv.view("tasksCalendar", {pages: "", view: "week", firstDayOfWeek: "1", startPosition: "2023-03", options: "style1"})
```

https://github.com/702573N/Obsidian-Tasks-Calendar#startposition

**Comment by foenixp** [comment]
It works! Thank you very much!
