### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by pcause** [702573N/Obsidian-Tasks-Calendar#6]
I like the way undated items are on top, but the dated items I'd like to see sorted by description.  A user posted on the forum that if you start the description with a time or time range and sort by description you get you day planner layout.  Perhaps the idea is to have a sort: parameter and then use values like tag, description and the like.  you could look at the tasks plugin for their options and apply that to each group of items in the day.  So done, undated, dated, each are sorted by that field.

I think also that recurring and other dated items should be sorted together.  People have recurring items as part of their day and in my example, I have the descriptions all set so they order to do my day planner

Thanks for the efforts.  This really is something that was sorely needed.  You might reach our to the maintainer of the tasks plugin and see if there is a way to combine efforts.

**Comment by claremacrae** [comment]
> Thanks for the efforts. This really is something that was sorely needed. You might reach our to the maintainer of the tasks plugin and see if there is a way to combine efforts.

Hi - maintainer of Tasks here.... Happy to try and help or work together, but I see you have fully implemented this using dataview - amazing!

**Comment by claremacrae** [comment]
In case it helps, here is how I implemented sorting by description in my local copy of this file:

```js
// Set Task And Append To Content Container
function setTaskContentContainer(currentDate) {
	var cellContent = "";

	function compareFn(a, b) {
	  if (a.text < b.text) {
		return -1;
	  }
	  if (a.text > b.text) {
		return 1;
	  }
	  // a must be equal to b
	  return 0;
	}

	function showTasks(tasksToShow, type) {
		const sorted = [...tasksToShow].sort(compareFn);
		for (var t = 0; t < sorted.length; t++) {
			cellContent += setTask(sorted[t], type)
		}
	}

	if (tToday == currentDate) {
		showTasks(overdue, "overdue");
	};
	showTasks(due, "due");
	showTasks(recurrence, "recurrence");
	showTasks(start, "start");
	showTasks(scheduled, "scheduled");
	showTasks(process, "process");
	showTasks(done, "done");
	showTasks(cancelled, "cancelled");
	return cellContent;
};
```

The original code was:

```js
function setTaskContentContainer(currentDate) {
	var cellContent = "";
	if (tToday == currentDate) {for (var t=0; t<overdue.length; t++) {cellContent += setTask(overdue[t], "overdue")}};
	for (var t=0; t<due.length; t++) {cellContent += setTask(due[t], "due")};
	for (var t=0; t<recurrence.length; t++) {cellContent += setTask(recurrence[t], "recurrence")};
	for (var t=0; t<start.length; t++) {cellContent += setTask(start[t], "start")};
	for (var t=0; t<scheduled.length; t++) {cellContent += setTask(scheduled[t], "scheduled")};
	for (var t=0; t<process.length; t++) {cellContent += setTask(process[t], "process")};
	for (var t=0; t<done.length; t++) {cellContent += setTask(done[t], "done")};
	for (var t=0; t<cancelled.length; t++) {cellContent += setTask(cancelled[t], "cancelled")};
	return cellContent;
};
```

**Comment by claremacrae** [comment]
The above is a case-sensitive sort. I don't know if that is what people might generally want...

**Comment by claremacrae** [comment]
Oh, I just realised that the above didn't sort tasks in the agenda view's backlog.

@702573N Please let me know if you would like me to submit a [pull request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-a-pull-request-in-github-desktop) for a full (case-sensitive) fix for this.
