### ISSUE TITLE
How to exclude recurring task from weekly view ?

### ISSUE THREAD

**Issue by mathisgauthey** [702573N/Obsidian-Tasks-Calendar#67]
Hi there, I'm using this repo as a mean to check for my upcoming tasks.

Is there a way for me to exclude by default done tasks and reccuring ones as well inside the command block ? I don't find a way, I can do it using the UI but can't find how to code it.

Thanks !

**Comment by ronny3** [comment]
Hi. I had this same wish. I implemented it in the dv.pages() function, as such: `pages: dv.pages().file.tasks.where(t => !t.text.includes("🔁"))`

Note that if you use the recurrence emoji elsewhere, you might run into issues.

LMK how it worked for you.

**Comment by mathisgauthey** [comment]
I'll give it a try tonight, thanks for your input !
