### ISSUE TITLE
widget causes page to flash when typing text 

### ISSUE THREAD

**Issue by pcause** [702573N/Obsidian-Tasks-Calendar#7]
I try to type some plain text in a page that has the widget at top and the page flashed on each character typed.  No sure if this is calendar code or  dataview or an interaction.  The text was not a task or in a task although the page does have task within it.

**Comment by 702573N** [comment]
Hi @pcause,
can you still observe this problem with the latest version?

**Comment by pcause** [comment]
kind of worse.  To get around the issue I put the dataview snippet in a callout that is not expanded by default.  When expanded, typing anything is bery, very slow and adding a task right underneath the the expanded calendar (using week view) causes flashes.  On Windows.

**Comment by 702573N** [comment]
I can understand that this behavior is very annoying, however, this behavior is summed up by many negative influencing factors.
In most use cases the embed and the note your are currently writing in, are not the same. In edit mode the dataviews where only rendered to preview, if this is enabled. This is a nice helping feature but can buggy when your vault is large and the embeded view is complex like task-calendar. The dataview plugin developer is warning this in settings.

![Unbenannt](https://user-images.githubusercontent.com/59178587/199955294-28314b1d-b8ba-4126-8076-b676f66b683f.png)

There are some things you can change:
- Disable preview render in edit mode
- Not embed calendar-views in notes you are writing in
- Reduce refresh rate of dataview plugin

At the moment, I don't see any other ways to stop this behavior.

**Comment by pcause** [comment]
I understand.  I work in preview view and I use the calendar at the top of my daily note.  I forgot about that option/issue.  Hate to turn off as I add items for today/future dates to my daily note all the time and use the week view to be sure there is  no conflict.  

Have turned that off now and will see how it works.   I guess I could put the calendar in a different file and transclude it and view with hover.

**Comment by 702573N** [comment]
My personal setup consists of a note pinned to the right sidebar, which is populated with a mini calendar, overdue callout, today callout, upcoming callout (next 7 days), progress callout, and backlog callout. With custom css snippet, each box get a custom color.

Maybe this could be something for you.

[Sidebar.md](https://github.com/702573N/Obsidian-Tasks-Calendar/files/9938142/Sidebar.md)

![Unbenannt](https://user-images.githubusercontent.com/59178587/199971394-24b55e77-13d6-4cf0-af8a-f2bb7481b007.png)

**Comment by pcause** [comment]
yes, similar idea.  my latest issue is that the colors changed and are all washed out.  I use a Nord scheme and items are unreadable.  Will open the debug panel and figure out what css i need for this.  I am closing but you might add something to the readme.
