### ISSUE TITLE
Click on task in File with quote in name creates empty file with truncated name

### ISSUE THREAD

**Issue by claremacrae** [702573N/Obsidian-Tasks-Calendar#8]
Hi, huge thanks for this amazing work. I'm currently trying it for myself on my own vault, and documenting it for users of the Tasks plugin!

I did find one small thing... As described in the summary above...

### Here are steps to reproduce:

1. Create a file with this content:

```text
# Fred's wheelchair

- [ ] Get a seatbelt 📅 2022-10-24 
```

2. And save it in `Fred's wheelchair.md`
3. Set up any calendar that matches the above task - for example:

````text

```dataviewjs
// view: month, widget, agenda
dv.view("_meta/_scripts/dvjs/tasks_calendar", {pages: "TESTING", view: "agenda", firstDayOfWeek: 1, options: "noDone"});
```
````

4. View in Reading mode

![image](https://user-images.githubusercontent.com/4840096/197566987-95901f00-3459-4ee6-9e19-2cfe6c872cce.png)

5. Click on the 'Get a seatbelt' task

**Expected behaviour:** Opens `Fred's wheelchair.md`
**Actual behaviour:** Creates a new file `Fred.md` using the default template

I'm just guessing: Maybe the file name or path needs to be encoded?

**Comment by 702573N** [comment]
OK, that's realy a strange problem. I've got the full path from "object.link.path" as string "Inbox/Jeanne D'Arc.md" in full length without cutting. This string is then used to replace a placeholder like "{{taskPath}}" in the task-template-html. The result is always "Inbox/Jeanne D". That makes no sense to me. I'm not a professional programmer. I try the encodeURI method but got the same result in ecoded stlye "Inbox/Jeanne%20D". Any ideas?

**Comment by 702573N** [comment]
Current solution: `.replace("'", "&apos;")` not perfect but works well.

Fixed with latest version of the view.js file. Rolled out with next release.

**Comment by claremacrae** [comment]
> OK, that's realy a strange problem. I've got the full path from "object.link.path" as string "Inbox/Jeanne D'Arc.md" in full length without cutting. This string is then used to replace a placeholder like "{{taskPath}}" in the task-template-html. The result is always "Inbox/Jeanne D". That makes no sense to me. I'm not a professional programmer. I try the encodeURI method but got the same result in ecoded stlye "Inbox/Jeanne%20D". Any ideas?

I'm sure you've figured this out, but the code must be quoting some strings in `'` - so the text with `'` gets written as:

`'Fred's Wheelchair'`

Which, when interpreted, gets truncated at the first `'` in the string to:

`'Fred'`

Thank you for the fix. It works great for this case.
