### ISSUE TITLE
How to show tasks from several folders?

### ISSUE THREAD

**Issue by claremacrae** [702573N/Obsidian-Tasks-Calendar#9]
In the pages parameter, is it possible to give it a list of several folders please? Or give it a list of folders to exclude?

I'm asking because I've got too many tasks for it to show every task in one calendar, and and there are some unrelated areas... So I would like to divide my 20 or so top-level folders in to about 4 different calendars....

**Comment by wenlzhang** [comment]
I was also going to ask something like this. With DataviewJS, one can use something like the following to search for tasks with certain tags while excluding certain folders: `dv.pages('(#ToDo or #Task) and -"Templates"')`

Can such combinations be supported here?

**Comment by 702573N** [comment]
The latest view.js file contains that change and will be part of the next release. The dv.pages command works exactly the same like in dataviewjs.

[https://github.com/702573N/Obsidian-Tasks-Calendar/blob/main/tasksCalendar/view.js](url)
